name: 🗃️ React Affise Issue
description: File a Detailed Issue.
title: "[Issue]: "
labels: 
  - bug
projects:
  - affise/affise-mmp-sdk-react
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        `Thanks for taking the time to fill out this Issue`
  - type: input
    id: version-tag
    attributes:
      label: Version
      description: Tell us Affise React library version
      placeholder: Version
    validations:
      required: true
  - type: dropdown
    id: react-device
    attributes:
      label: Device
      description: On which device you running
      multiple: true
      options:
        - Android
        - iOS
        - Neither
    validations:
      required: true
  - type: textarea
    id: react-doctor
    attributes:
      label: React Doctor
      description: Tell us, output for `npx react-native doctor` command
      placeholder: Tell us what `npx react-native doctor` says!
      render: shell
    validations:
      required: true
  - type: textarea
    id: react-info
    attributes:
      label: React Info
      description: Tell us, output for `npx react-native info` command
      placeholder: Tell us what `npx react-native info` says!
      render: shell
    validations:
      required: true
  - type: textarea
    id: issue-what-happened
    attributes:
      label: What happened?
      description: |
        - What did happen?
        - What did you expect to happen?
        - Give as much detail
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: issue-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Logs
      render: shell
  - type: textarea
    id: issue-code
    attributes:
      label: Code which cause a issue
      description: Please copy and paste any relevant Code. This will be automatically formatted into TypeScript code, so no need for backticks.
      placeholder: TypeScript code
      render: typescript
  - type: checkboxes
    id: issue-check
    attributes:
      label: I have
      options:
        - label: Read [documentation](https://github.com/affise/affise-mmp-sdk-react/README.md)
          required: true
        - label: Tried [Troubleshoots](https://github.com/affise/affise-mmp-sdk-react/README.md#Troubleshoots)
          required: true
    validations:
      required: true
    
  - type: checkboxes
    id: issue-check-cache
    attributes:
      label: Tried reset cache?
      description: |
        - `npm cache verify`
        - `npm cache clean --force`
      options:
        - label: I have
          required: true
    validations:
      required: true
    
  - type: checkboxes
    id: issue-check-restart
    attributes:
      label: Did full application restart?
      description: |
        - `completely stop application on device`
        - `stop React server`
      options:
        - label: I have
          required: true
    validations:
      required: true