require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

target 'AffiseAttributionLibExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  affise_version = '1.7.14'
  # Affise Modules
  pod 'AffiseModule/Advertising', affise_version
  pod 'AffiseModule/AppsFlyer', affise_version
  pod 'AffiseModule/Status', affise_version
  pod 'AffiseModule/Persistent', affise_version
  pod 'AffiseModule/Link', affise_version
  pod 'AffiseModule/Subscription', affise_version
  pod 'AffiseModule/TikTok', affise_version

  target 'AffiseAttributionLibExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.targets.each do |target|
        next unless target.name == 'AffiseAttributionLibExample'

        target.build_configurations.each do |config|
          definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          definitions = [definitions] unless definitions.is_a?(Array)
          definitions << 'FOLLY_CFG_NO_COROUTINES=1' unless definitions.include?('FOLLY_CFG_NO_COROUTINES=1')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
        end
      end

      aggregate_target.user_project.save
    end
  end
end
