import {
  AchieveLevelEvent,
  AddPaymentInfoEvent,
  AddToCartEvent,
  AddToWishlistEvent,
  AdRevenueEvent,
  AffiseEvent,
  ClickAdvEvent,
  CompleteRegistrationEvent,
  CompleteStreamEvent,
  CompleteTrialEvent,
  CompleteTutorialEvent,
  ContactEvent,
  ContentItemsViewEvent,
  ConvertedOfferEvent,
  ConvertedOfferFromRetryEvent,
  ConvertedTrialEvent,
  ConvertedTrialFromRetryEvent,
  CustomId01Event,
  CustomId02Event,
  CustomId03Event,
  CustomId04Event,
  CustomId05Event,
  CustomId06Event,
  CustomId07Event,
  CustomId08Event,
  CustomId09Event,
  CustomId10Event,
  CustomizeProductEvent,
  DeepLinkedEvent,
  DonateEvent,
  FailedOfferFromRetryEvent,
  FailedOfferiseEvent,
  FailedSubscriptionEvent,
  FailedSubscriptionFromRetryEvent,
  FailedTrialEvent,
  FailedTrialFromRetryEvent,
  FindLocationEvent,
  InitialOfferEvent,
  InitialSubscriptionEvent,
  InitialTrialEvent,
  InitiateCheckoutEvent,
  InitiatePurchaseEvent,
  InitiateStreamEvent,
  InviteEvent,
  LastAttributedTouchEvent,
  LeadEvent,
  ListViewEvent,
  LoginEvent,
  OfferInRetryEvent,
  OpenedFromPushNotificationEvent,
  OrderCancelEvent,
  OrderEvent,
  OrderItemAddedEvent,
  OrderItemRemoveEvent,
  OrderReturnRequestCancelEvent,
  OrderReturnRequestEvent,
  PurchaseEvent,
  RateEvent,
  ReactivatedSubscriptionEvent,
  ReEngageEvent,
  RenewedSubscriptionEvent,
  RenewedSubscriptionFromRetryEvent,
  ReserveEvent,
  SalesEvent,
  ScheduleEvent,
  SearchEvent,
  ShareEvent,
  SpendCreditsEvent,
  StartRegistrationEvent,
  StartTrialEvent,
  StartTutorialEvent,
  SubmitApplicationEvent,
  SubscribeEvent,
  SubscriptionInRetryEvent,
  TravelBookingEvent,
  TrialInRetryEvent,
  UnlockAchievementEvent,
  UnsubscribeEvent,
  UnsubscriptionEvent,
  UpdateEvent,
  ViewAdvEvent,
  ViewCartEvent,
  ViewContentEvent,
  ViewItemEvent,
  ViewItemsEvent,
} from 'affise-attribution-lib';

export class SimpleEventsFactory {
  createEvents(): AffiseEvent[] {
    return [
      new AchieveLevelEvent(),
      new AddPaymentInfoEvent(),
      new AddToCartEvent(),
      new AddToWishlistEvent(),
      new AdRevenueEvent(),
      new ClickAdvEvent(),
      new CompleteRegistrationEvent(),
      new CompleteStreamEvent(),
      new CompleteTrialEvent(),
      new CompleteTutorialEvent(),
      new ContactEvent(),
      new ContentItemsViewEvent(),
      new CustomId01Event(),
      new CustomId02Event(),
      new CustomId03Event(),
      new CustomId04Event(),
      new CustomId05Event(),
      new CustomId06Event(),
      new CustomId07Event(),
      new CustomId08Event(),
      new CustomId09Event(),
      new CustomId10Event(),
      new CustomizeProductEvent(),
      new DeepLinkedEvent(),
      new DonateEvent(),
      new FindLocationEvent(),
      new InitiateCheckoutEvent(),
      new InitiatePurchaseEvent(),
      new InitiateStreamEvent(),
      new InviteEvent(),
      new LastAttributedTouchEvent(),
      new LeadEvent(),
      new ListViewEvent(),
      new LoginEvent(),
      new OpenedFromPushNotificationEvent(),
      new OrderEvent(),
      new OrderItemAddedEvent(),
      new OrderItemRemoveEvent(),
      new OrderCancelEvent(),
      new OrderReturnRequestCancelEvent(),
      new OrderReturnRequestEvent(),
      new PurchaseEvent(),
      new RateEvent(),
      new ReEngageEvent(),
      new ReserveEvent(),
      new SalesEvent(),
      new ScheduleEvent(),
      new SearchEvent(),
      new ShareEvent(),
      new SpendCreditsEvent(),
      new StartRegistrationEvent(),
      new StartTrialEvent(),
      new StartTutorialEvent(),
      new SubmitApplicationEvent(),
      new SubscribeEvent(),
      new TravelBookingEvent(),
      new UnlockAchievementEvent(),
      new UnsubscribeEvent(),
      new UpdateEvent(),
      new ViewAdvEvent(),
      new ViewCartEvent(),
      new ViewContentEvent(),
      new ViewItemEvent(),
      new ViewItemsEvent(),
      new InitialSubscriptionEvent(),
      new InitialTrialEvent(),
      new InitialOfferEvent(),
      new FailedTrialEvent(),
      new FailedOfferiseEvent(),
      new FailedSubscriptionEvent(),
      new FailedTrialFromRetryEvent(),
      new FailedOfferFromRetryEvent(),
      new FailedSubscriptionFromRetryEvent(),
      new TrialInRetryEvent(),
      new OfferInRetryEvent(),
      new SubscriptionInRetryEvent(),
      new ConvertedTrialEvent(),
      new ConvertedOfferEvent(),
      new ReactivatedSubscriptionEvent(),
      new RenewedSubscriptionEvent(),
      new ConvertedTrialFromRetryEvent(),
      new ConvertedOfferFromRetryEvent(),
      new RenewedSubscriptionFromRetryEvent(),
      new UnsubscriptionEvent(),
    ];
  }
}
