export enum AffiseModules {
    ADSERVICE = "AdService",
    ADVERTISING = "Advertising",
    ANDROIDID = "AndroidId",
    APPSFLYER = "AppsFlyer",
    LINK = "Link",
    META = "Meta",
    NETWORK = "Network",
    PERSISTENT = "Persistent",
    PHONE = "Phone",
    STATUS = "Status",
    SUBSCRIPTION = "Subscription",
    RUSTORE = "RuStore",
    HUAWEI = "Huawei",
}
