name: NPM Token Check
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  token:
    name: NPM Token Check
    runs-on: ubuntu-latest

    steps:
      - name: NPM Token
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: NPM Token Check
        run: |
          npm whoami

      - name: Tg Token Invalid
        continue-on-error: true
        id: tg_failed
        if: ${{ failure() }}
        uses: cbrgm/telegram-github-action@v1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          parse-mode: markdown
          disable-web-page-preview: true
          message: |
            ‼️ NPM token is invalid ‼️

            [Github Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})