name: 🏗️ Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  id-token: write  # Required for OIDC
  contents: write  # Grant write permissions for the GITHUB_TOKEN

jobs:
  publish:
    name: Publish Affise Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "NPM_CACHE=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache.outputs.NPM_CACHE }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: NPM Install
        run: |
          npm ci

      - name: NPM Publish Release
        if: ${{ !contains(github.event.ref, '-') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: |
          npm who
          npm publish 

      - name: NPM Publish Beta
        if: contains(github.event.ref, '-beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: |
          npm who
          npm publish --tag beta

      - name: Version Tag
        id: version_tag
        run: |
          echo Version: ${GITHUB_REF_NAME}
          echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Tg Release failed
        id: tg_failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🔴 React Native ${{ steps.version_tag.outputs.VERSION }} release failed

            [Github Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Tg Release
        id: tg_success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🟢 React Native ${{ steps.version_tag.outputs.VERSION }} release

            [Changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)

      - name: Release
        if: ${{ !contains(github.event.ref, '-') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Affise Attribution React Native Library ${{ github.ref }}
          draft: false
          prerelease: false
