name: 🏗️ Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  id-token: write  # Required for OIDC
  contents: write  # Grant write permissions for the GITHUB_TOKEN

jobs:
  publish:
    name: Publish Affise Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Version Tag
        id: version_tag
        run: |
          echo Version: ${GITHUB_REF_NAME}
          echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
    
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'

      - name: NPM Token
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: NPM Token Check
        run: |
          npm whoami

      - name: Invalid Token
        id: token_invalid
        if: ${{ failure() }}
        run: echo "Invalid NPM Token"

      - name: Tg Token Invalid
        continue-on-error: true
        id: tg_npm_failed
        if: ${{ failure() }}
        uses: cbrgm/telegram-github-action@v1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          parse-mode: markdown
          disable-web-page-preview: true
          message: |
            ‼️ NPM token is invalid ‼️

            [Github Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "NPM_CACHE=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache.outputs.NPM_CACHE }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Package affise-attribution-lib
      - name: NPM Install
        working-directory: affise-attribution-lib
        run: npm ci

      - name: Publish attribution-lib
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta attribution-lib
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-adservice
      - name: NPM Install
        working-directory: affise-attribution-module-adservice
        run: npm install

      - name: Publish module-adservice
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-adservice
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-adservice
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-adservice
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-advertising
      - name: NPM Install
        working-directory: affise-attribution-module-advertising
        run: npm install

      - name: Publish module-advertising
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-advertising
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-advertising
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-advertising
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-androidid
      - name: NPM Install
        working-directory: affise-attribution-module-androidid
        run: npm install

      - name: Publish module-androidid
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-androidid
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-androidid
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-androidid
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-appsflyer
      - name: NPM Install
        working-directory: affise-attribution-module-appsflyer
        run: npm install

      - name: Publish module-appsflyer
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-appsflyer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-appsflyer
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-appsflyer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-google
      - name: NPM Install
        working-directory: affise-attribution-module-google
        run: npm install

      - name: Publish module-google
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-google
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-google
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-google
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-huawei
      - name: NPM Install
        working-directory: affise-attribution-module-huawei
        run: npm install

      - name: Publish module-huawei
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-huawei
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-huawei
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-huawei
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-link
      - name: NPM Install
        working-directory: affise-attribution-module-link
        run: npm install

      - name: Publish module-link
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-link
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-link
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-link
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-meta
      - name: NPM Install
        working-directory: affise-attribution-module-meta
        run: npm install

      - name: Publish module-meta
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-meta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-meta
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-meta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-network
      - name: NPM Install
        working-directory: affise-attribution-module-network
        run: npm install

      - name: Publish module-network
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-network
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-network
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-network
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-persistent
      - name: NPM Install
        working-directory: affise-attribution-module-persistent
        run: npm install

      - name: Publish module-persistent
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-persistent
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-persistent
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-persistent
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-phone
      - name: NPM Install
        working-directory: affise-attribution-module-phone
        run: npm install

      - name: Publish module-phone
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-phone
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-phone
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-phone
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-rustore
      - name: NPM Install
        working-directory: affise-attribution-module-rustore
        run: npm install

      - name: Publish module-rustore
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-rustore
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-rustore
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-rustore
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-status
      - name: NPM Install
        working-directory: affise-attribution-module-status
        run: npm install

      - name: Publish module-status
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-status
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-status
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-status
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-subscription
      - name: NPM Install
        working-directory: affise-attribution-module-subscription
        run: npm install

      - name: Publish module-subscription
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-subscription
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-subscription
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-subscription
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      # Package affise-attribution-module-tiktok
      - name: NPM Install
        working-directory: affise-attribution-module-tiktok
        run: npm install

      - name: Publish module-tiktok
        if: ${{ !contains(github.event.ref, '-') }}
        working-directory: affise-attribution-module-tiktok
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish

      - name: Publish Beta module-tiktok
        if: contains(github.event.ref, '-beta')
        working-directory: affise-attribution-module-tiktok
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # skip for OIDC
        run: npm publish --tag beta

      - name: Tg Release failed
        continue-on-error: true
        id: tg_failed
        if: ${{ steps.token_invalid.outcome == 'skipped' && failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🔴 React Native `${{ steps.version_tag.outputs.VERSION }}` release failed

            [Github Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Tg Release
        continue-on-error: true
        id: tg_success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🟢 React Native `${{ steps.version_tag.outputs.VERSION }}` release

            [Changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)

      - name: Release
        if: ${{ !contains(github.event.ref, '-') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Affise Attribution React Native Library ${{ github.ref }}
          draft: false
          prerelease: false
